site_name: Vercel-MkDocs-Material
site_url: https://vercel-mkdocs-material.vercel.app/
site_description: Vercel-MkDocs-Material is a Material Design theme for MkDocs, a static site generator geared towards (technical) project documentation. It is built with Material Components for the Web, a framework that implements Material Design guidelines from Google.
site_author: Akihiko Shirai
site_dir: public

theme:
  name: material
  palette:
    primary: indigo
    accent: pink
  font:
    text: Noto Sans JP
    code: Inconsolata
  features:
    - content.code.annotate
    - navigation.tabs
    - navigation.sticky
#    - navigation.sections
    - navigation.top
    - header.autohide
  icon:
    repo: fontawesome/brands/github
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: red
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

nav:
  - Home: index.md
  - Blog: blog/
  - About: about.md

plugins:
  search:
    lang: 'ja'
  blog: #https://squidfunk.github.io/mkdocs-material/plugins/blog/#config.blog_dir
#    blog_dir: .
    blog_toc: true
#   post_url_format: # default is yyyy/mm/dd/{slug}
#    post_slugify: !!python/object/apply:pymdownx.slugs.slugify
#    kwds:
#    case: lower
  tags:

extra:
#  analytics:
#    provider: google
#    property: G-DQDGMD4GSE
  alternate:
    - name: English
      link: /
      lang: en
    - name: Japanese
      link: /ja/
      lang: ja
  consent:
    title: Cookie consent
    description:
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  social:
    - icon: fontawesome/brands/twitter
      link: https://x.com/o_ob
      name: o_ob on X
    - icon: fontawesome/brands/github
      link: https://github.com/kaitas/vercel-mkdocs-material
  generator: false

extra_javascript: 
  - javascripts/github-calendar.min.js
  - https://platform.twitter.com/widgets.js
  - js/custom_twitter.js
#  - js/mathjax.js
#  - https://polyfill.io/v3/polyfill.min.js?features=es6
#  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
extra_css:
  - stylesheets/github-calendar-responsive.css
  - stylesheets/extra.css # https://squidfunk.github.io/mkdocs-material/customization/#additional-css
  - https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css

