site_name: Vercel-MkDocs-Material
site_description: Vercel-MkDocs-Material is a Material Design theme for MkDocs, a static site generator geared towards (technical) project documentation. It is built with Material Components for the Web, a framework that implements Material Design guidelines from Google.
site_author: Akihiko Shirai

theme:
  name: material
  palette:
    primary: indigo
    accent: pink
  font:
    text: Noto Sans JP
    code: Inconsolata
  features:
    - content.code.annotate
    - navigation.tabs
    - navigation.sticky
#    - navigation.sections
    - navigation.top
    - header.autohide
  icon:
    repo: fontawesome/brands/github
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: red
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

nav:
  - Home: index.md
  - Blog: blog/
  - About: about.md

plugins:
  search:
    lang: 'ja'
  blog: #https://squidfunk.github.io/mkdocs-material/plugins/blog/#config.blog_dir
#    blog_dir: .
    blog_toc: true
#   post_url_format: # default is yyyy/mm/dd/{slug}
#    post_slugify: !!python/object/apply:pymdownx.slugs.slugify
#    kwds:
#    case: lower
  tags:
